[package]
name = "zigbee"
version = "0.1.0"
authors = ["Gianmarco Garrisi <gianmarcogarrisi@tutanota.com>"]
description = "An API for zigbee: Low-power, low-cost, low-complexity networking for the Internet of Things"

[dependencies]
